default_boxes = [
    {
        "name": "Computers",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": 3,
        "fragile": True,
        "liquid": False,
        "valuable": True,
        "weather_resistant": False,
    },
    {
        "name": "Food Staples",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": 2,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": False,
    },
    {
        "name": "TV Stand 1",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": False,
    },
    {
        "name": "TV Stand 3",
        "size": "small",
        "length": 17,
        "width": 11,
        "height": 11,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": False,
    },
    {
        "name": "TV Stand 2",
        "size": "small",
        "length": 17,
        "width": 11,
        "height": 11,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": False,
    },
    {
        "name": "Bathroom",
        "size": "small",
        "length": 11,
        "width": 17,
        "height": 11,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": True,
    },
    {
        "name": "Kitchen 1 of 2",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": 1,
        "fragile": True,
        "liquid": False,
        "valuable": True,
        "weather_resistant": False,
    },
    {
        "name": "Kitchen 2 of 2",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": 2,
        "fragile": False,
        "liquid": False,
        "valuable": True,
        "weather_resistant": False,
    },
    {
        "name": "Black Tote",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": 2,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": True,
    },
    {
        "name": "Big Clock Box",
        "size": "xlarge",
        "length": 24,
        "width": 21,
        "height": 20,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": False,
    },
    {
        "name": "Yellow Lid Tote",
        "size": "xlarge",
        "length": 30,
        "width": 20,
        "height": 15,
        "weight_class": 3,
        "fragile": True,
        "liquid": False,
        "valuable": False,
        "weather_resistant": False,
    },
    {
        "name": "Games",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": True,
    },
    {
        "name": "Costumes",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": True,
    },
    {
        "name": "Computer Monitors",
        "size": "xlarge",
        "length": 24,
        "width": 21,
        "height": 20,
        "weight_class": 3,
        "fragile": True,
        "liquid": False,
        "valuable": True,
        "weather_resistant": False,
    },
    {
        "name": "Liquids",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": 3,
        "fragile": False,
        "liquid": True,
        "valuable": False,
        "weather_resistant": True,
    },
    {
        "name": "Misc Bedroom",
        "size": "small",
        "length": 11,
        "width": 17,
        "height": 11,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": True,
    },
    {
        "name": "Misc Accessories",
        "size": "small",
        "length": 17,
        "width": 11,
        "height": 11,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": True,
    },
    {
        "name": "Green Duffel",
        "size": "small",
        "length": 17,
        "width": 11,
        "height": 11,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": False,
    },
    {
        "name": "Clothes",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": 2,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": False,
    },
    {
        "name": "Computer Equipment",
        "size": "small",
        "length": 17,
        "width": 11,
        "height": 11,
        "weight_class": 1,
        "fragile": False,
        "liquid": False,
        "valuable": False,
        "weather_resistant": False,
    },
    {
        "name": "Desk Equivalent",
        "size": "medium",
        "length": 21,
        "width": 16,
        "height": 15,
        "weight_class": "heavy",
        "fragile": False,
        "liquid": False,
        "valuable": True,
        "weather_resistant": False,
    },
]
